apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: ghcr.io/mostafasery/microservices:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcr-secret

